// packages/shared/src/protocol.ts
// 向后兼容的 re-export barrel —— 拆分到 protocol/ 下各个领域模块

export {
  SessionStatus,
  AnalysisStatus,
  WritebackStatus,
  ALLOWED_COMMANDS,
  DESTRUCTIVE_COMMANDS,
  ALLOWED_EVENTS,
  isRecord,
} from './protocol/core'
export type {
  ResponseOk,
  ResponseErr,
  Response,
  Command,
  Event,
  ProgressData,
  EngineStatusData,
  C1ImportData,
  C1PluginImportData,
  ExportProgressData,
  ModelDownloadProgressData,
  JobProgressData,
  GroupData,
  WritebackAttributes,
  WritebackOptions,
  WritebackPreview,
  WritebackItem,
  WritebackResult,
  CleanupResult,
  AddPhotoResult,
  ThumbnailGetParams,
  ImageGetPreviewParams,
  ImageGetThumbnailParams,
  ImagePreviewResult,
} from './protocol/core'

export type {
  SessionCreateParams,
  SessionDeleteParams,
  SessionDeleteManyParams,
  SessionAddPhotosParams,
  SessionGetParams,
  SessionUpdateParams,
  SessionData,
  PhotoData,
} from './protocol/session'

export type {
  FkwAnalyzeParams,
  FkwCancelAnalysisParams,
  FkwClustersParams,
  FkwBindParams,
  FkwUnbindParams,
  FkwMergeParams,
  FkwRemoveMemberParams,
  FkwPreviewParams,
  FkwWritebackParams,
  FkwConfirmSyncParams,
  FkwConfirmCleanupParams,
  FkwCleanupParams,
  FaceModelsStatusData,
  FaceObservation,
  FaceCluster,
  ClusterMember,
  BindingData,
} from './protocol/face'

export type {
  SimAnalyzeParams,
  SimCancelAnalysisParams,
  SimResultParams,
  SimReclusterParams,
  SimPreviewWritebackParams,
  SimWritebackParams,
  SimWritebackItemsParams,
  SimRetryFailedWritebackParams,
  SimConfirmSyncParams,
  SimCleanupParams,
  SimilarityKeywordAssignment,
  SimilarityGroupingMode,
  SimilarityGroup,
  SimilarityImage,
} from './protocol/similarity'

export type {
  PersonListParams,
  PersonGetParams,
  PersonCreateParams,
  PersonUpdateParams,
  PersonDeleteParams,
  PersonMergeParams,
  PersonRemovePhotoParams,
  PersonSearchPhotosParams,
  PersonData,
  PersonDetailData,
  PersonPhotoItem,
} from './protocol/person'

export type {
  MetadataGetParams,
  MetadataSetParams,
  MetadataBatchSetParams,
  MetadataField,
  MetadataMutationSource,
  MetadataPatch,
  MetadataMutationRequest,
  MetadataMutationResult,
  MetadataConflictField,
  MetadataConflict,
  MetadataConflictChoice,
  MetadataConflictListParams,
  MetadataConflictResolveParams,
  MetadataOrphan,
  MetadataOrphanResolveParams,
  MetadataTags,
  BatchMetadataResult,
} from './protocol/metadata'

export type {
  AnalysisJobType,
  AnalysisJobStatus,
  AnalysisJobData,
  JobCreateParams,
  JobListParams,
  JobCancelParams,
  JobRetryParams,
  JobClearCompletedParams,
  JobProgressUpdate,
} from './protocol/jobs'

export type { IndexScanParams, IndexScanResult } from './protocol/indexer'
export type {
  AssetCandidateListParams,
  AssetCandidateMutationParams,
  AssetLinkCandidateData,
  AssetVolumeData,
  AssetRelinkRootParams,
} from './protocol/assets'
export type { QualityAnalyzeParams, QualityGetParams, QualityResult } from './protocol/quality'
export type {
  NavigationAnalyzeParams,
  NavigationListParams,
  NavigationSplitParams,
  NavigationMergeParams,
  NavigationGroup,
  NavigationGroupType,
} from './protocol/navigation'
export type {
  DupScanParams,
  DupGroupsParams,
  DupResolveParams,
  DupResolveMemberParams,
  DupScanOptions,
  DuplicateScanResult,
  DuplicateGroup,
  DuplicateGroupMember,
} from './protocol/duplicate'

export type {
  FilterPhotosParams,
  FilterPhotosGlobalParams,
  FilterSuggestParams,
  AlbumCreateParams,
  AlbumListParams,
  AlbumGetParams,
  AlbumUpdateParams,
  AlbumDeleteParams,
  AlbumGetPhotosParams,
  FilterRule,
  FilterGroup,
  FilterSuggestion,
  GlobalPhotoResult,
  SmartAlbumData,
  SmartAlbumDetailData,
} from './protocol/filter'

export type {
  ExportPreviewParams,
  ExportExecuteParams,
  ExportCancelParams,
  ExportReportParams,
  ExportOptions,
  ExportPreview,
  ExportResult,
  ReportData,
} from './protocol/export'

export type {
  TemplateCreateParams,
  TemplateListParams,
  TemplateGetParams,
  TemplateUpdateParams,
  TemplateDeleteParams,
  TemplateApplyParams,
  WorkflowTemplateConfig,
  TemplateData,
} from './protocol/template'

export type {
  PickState,
  LegacyCullingDecision,
  CaptureOneColorLabel,
  CullingScope,
  MetadataSyncStatus,
  CullingFilters,
  AssetCullingState,
  CullingAsset,
  CullingListParams,
  CullingUpdatePatch,
  CullingUpdateParams,
  CullingUpdateResult,
  CullingBatchUpdateParams,
  CullingDecideGroupParams,
  CullingSyncStatusParams,
  CullingFlushParams,
  CullingRetrySyncParams,
  CullingFinalizeSyncParams,
  MetadataSyncItem,
  MetadataSyncSummary,
  CullingGroupsParams,
  CullingDecideParams,
  CullingBatchDecideParams,
  CullingSummaryParams,
  CullingWritebackParams,
  CullingRetryWritebackParams,
  CullingConfirmSyncParams,
  CullingCleanupParams,
  CullingResetParams,
  CullingHistoryEntry,
  CullingHistoryOperation,
  CullingHistoryParams,
  CullingHistoryApplyEntry,
  CullingHistoryApplyParams,
  CullingGroup,
  CullingImage,
  CullingSummary,
} from './protocol/culling'
